services:
  dfs_go_auth:
    container_name: dfs_go_auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - dfs_db_postgres
    ports:
      - "8080:8080"
    networks:
      - default
    restart: on-failure

  dfs_db_postgres:
    image: postgres:latest
    container_name: dfs_db_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - default